title:
  name: Gtool API Client
  description: "Something good"
user: dougEfresh
project: lambdazap
installation: >-
  ```shell

  $ go get -u github.com/dougEfresh/

  ```
quickStart:
  code: |
    ```go

    ```
  description: ""
examples:
  - "Example 1"
  - "Example 2"
tests:
  - |
    ```shell
    $ go test -v

    ```